Repository googleapis/python-talent, pull requests merged in 2020-12, with the labels that each got.

#43 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: jobs, cla: yes, samples

#56 chore: reorder classes and exceptions
  google/cloud/talent_v4/__init__.py
  google/cloud/talent_v4beta1/__init__.py
  google/cloud/talent_v4beta1/services/application_service/async_client.py
  google/cloud/talent_v4beta1/services/application_service/transports/base.py
  google/cloud/talent_v4beta1/services/company_service/async_client.py
  google/cloud/talent_v4beta1/services/company_service/transports/base.py
  google/cloud/talent_v4beta1/services/completion/async_client.py
  google/cloud/talent_v4beta1/services/completion/transports/base.py
  google/cloud/talent_v4beta1/services/job_service/async_client.py
  google/cloud/talent_v4beta1/services/job_service/transports/base.py
  google/cloud/talent_v4beta1/services/profile_service/async_client.py
  google/cloud/talent_v4beta1/services/profile_service/transports/base.py
  google/cloud/talent_v4beta1/services/tenant_service/async_client.py
  google/cloud/talent_v4beta1/services/tenant_service/transports/base.py
Labels: api: jobs, cla: yes, context: none

#58 chore: update templates
  .flake8
  .kokoro/docs/common.cfg
  .kokoro/test-samples.sh
  .pre-commit-config.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: jobs, cla: yes, context: partial

#60 chore: reorder classes and exceptions
  google/cloud/talent_v4/__init__.py
  google/cloud/talent_v4beta1/__init__.py
  google/cloud/talent_v4beta1/services/application_service/async_client.py
  google/cloud/talent_v4beta1/services/application_service/transports/base.py
  google/cloud/talent_v4beta1/services/company_service/async_client.py
  google/cloud/talent_v4beta1/services/company_service/transports/base.py
  google/cloud/talent_v4beta1/services/completion/async_client.py
  google/cloud/talent_v4beta1/services/completion/transports/base.py
  google/cloud/talent_v4beta1/services/job_service/async_client.py
  google/cloud/talent_v4beta1/services/job_service/transports/base.py
  google/cloud/talent_v4beta1/services/profile_service/async_client.py
  google/cloud/talent_v4beta1/services/profile_service/transports/base.py
  google/cloud/talent_v4beta1/services/tenant_service/async_client.py
  google/cloud/talent_v4beta1/services/tenant_service/transports/base.py
  synth.metadata
Labels: api: jobs, cla: yes, context: none
